# This is an example Mocha config containing every Mocha option plus others.
color: true
diff: true
extension: ['ts']
require: 'ts-node/register/transpile-only'
spec:
  - './**/*.spec.ts' # the positional arguments!
